### ISSUE TITLE
Implement bandpass in the sim_sso pipeline

### ISSUE THREAD

**Issue by Zhilei** [simonsobs/sotodlib#109]
For future work...

**Comment by keskitalo** [comment]
Example of getting the bandpasses and applying them to atmospheric emission: https://github.com/hpc4cmb/toast/blob/master/src/toast/pipeline_tools/atm.py#L417-L437

**Comment by nad-dch** [comment]
Thanks Reijo and Zhilei. I will look at the code and come back with questions if needed.

**Comment by Zhilei** [comment]
Closing the issue since it has been addressed in #108.
