### ISSUE TITLE
Detector positions in SSO sim aren't as expected

### ISSUE THREAD

**Issue by mhasself** [simonsobs/sotodlib#157]
Extracting detector positions from a Jupiter sim on SAT1 w29 gives this focal plane map:

![image](https://user-images.githubusercontent.com/1054988/131585729-73071e87-cd25-48ef-b92c-86f42c5ee5a4.png)

Note the notch in lower right (x=-1.8, y=-13.5).  The instrument model doc and the output of so_hardware_plot produce this image for w29:

![image](https://user-images.githubusercontent.com/1054988/131585891-c1297feb-6b3a-4109-853a-5ae04d6ca07c.png)

I believe we all think we're plotting the same thing here -- the detector positions, as they project onto the sky, with the horizontal axis of the plot parallel to lines of constant elevation.

@smsimon @tskisner  I believe this is a simple matter of interchanging "x" and "y" coordinates, when you plot your detector position data.  But as discussed elsewhere it might be good to review the coordinate systems so everything is clear.

**Comment by Zhilei** [comment]
Hi, Matthew. This is really great! Thank you so much for spending time looking into this!
