### ISSUE TITLE
AxisManager should accommodate scalars

### ISSUE THREAD

**Issue by mhasself** [simonsobs/sotodlib#176]
AxisManager can't handle scalars (not even scalar arrays).  It probably should.

As suggested most recently by @amaurea , for pointing matrix support (weather and site info), but I know this is something many people have wondered about.  There are obviously many use cases in the detector setup realm.

**Comment by kmharrington** [comment]
I've realized this would be super super useful because then we could merge all the details in the `SmurfStatus` object into an AxisManager.

**Comment by skhrg** [comment]
Started taking a whack at this (https://github.com/simonsobs/sotodlib/tree/axisman_scalars)
What's unclear to me is if there is some meaningful equivalent of `restriction` and `intersection` for scalars. 

Comments/suggestions would be appreciated.

**Comment by kmharrington** [comment]
Great to see work on this! The easiest way for us to get comments on the specific code might be to make a draft pull request (it let's us comment on individual lines / have discussions on different parts of the code.

I'm confused what you mean by a scalar array in this instance, could you maybe share an example of your the expected use case for that one? And/or also for just general scalars?

**Comment by skhrg** [comment]
Good point, draft PR is #200 

As far as scalar arrays go, I am not too sure what the use case is, more of a I didn't see a reason not to allow it sort of thing (ie: calling `resolve` with `src` that is an array rather than a single scalar doesn't cause an issue).

**Comment by mhasself** [comment]
Closed via #200
