### ISSUE TITLE
Example SAT FWHMs are copied from LAT

### ISSUE THREAD

**Issue by keskitalo** [simonsobs/sotodlib#189]
https://github.com/simonsobs/sotodlib/blob/2f12285d5028b2595479efe16e5c1f6c36523411/sotodlib/sim_hardware.py#L1088-L1093

**Comment by keskitalo** [comment]
Oops! The FWHMs are scaled later in the file.

**Comment by smsimon** [comment]
Yeah, these are a just place holder for the actual SAT beams, which we hope to get in the future. I wanted to build in the functionality so we can add them in whenever we do get them!

**Comment by keskitalo** [comment]
I'm pretty sure I tripped on this during the PR review as well. At least I am consistent!
