### ISSUE TITLE
G3tSmurf: Make bias group maps easily accessible

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sotodlib#219]
Now that we have more official / complete `sodetlib` bias group maps coming out we should take our version in `latrt-testing` and add it into sotodlib so that it's easily accessible. Eventually it will run through caldbs / the metadata system but for now lets make something that can be automatically loaded and used. The backend loading can get updated once we have a better detdb / caldb setup for g3tsmurf.

**Comment by kmharrington** [comment]
Question for @jseibert575 @skhrg @jeffiuliano @jlashner 

With Calibration operations now in the G3tSmurf databases and the ability to get paths of all the files associated those observations [here](https://github.com/simonsobs/sotodlib/blob/master/sotodlib/io/g3tsmurf_utils.py#L31). Do we consider this enough to make bias group maps "easily accessible?"

**Comment by skhrg** [comment]
This is good with me. Historically I've been globbing for the path based on a timestamp so this is an improvement for sure.
