### ISSUE TITLE
Change Context.get_meta to include detector cuts?

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sotodlib#233]
Something I found while working on CalDb loading.

Right now if I generate the loading logic using `Context.get_obs()` like this:
```
request = context.get_obs( obs_id=my_id, dets=det_list, logic_only=True )
```
and then I want to just load the metadata I would call this:
```
meta = context.get_meta(request['request'])
```

But I'd really like to have the metadata returned only including the detectors in `det_list`.  Looking through `get_obs`, it looks like the metadata downselect happens when the metadata AxisManager / ResultSet is merged with the AxisManager with the loaded detector data. 

Could we change `get_meta` to take the full `logic_only=True` return of `get_obs`? Or accept a `dets` argument? Something where we can just get the metadata for some detectors.

**Comment by mhasself** [comment]
Enabled through #265 .
