### ISSUE TITLE
HWP Angle Calculator hangs on (possibly) bad data

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sotodlib#319]
Working on testing out the update script using `/mnt/so1/data/ucsd-sat1/hk/16664/1666404558.g3` (@jseibert575 may have other examples). 

We know something went wrong with the IRIG timing around then, so we might not want this data anyway, but we need the automatic calculator to know when to give up and move on. Could we add some sort of checks so this data doesn't cause issues with the automated analysis?

**Comment by yukisakurai** [comment]
Thank you pointing out of this. It is known hardware issue but we need to deal with it by software side for automatic processing.

IRIG timing is unstable and has spikes in`/mnt/so1/data/ucsd-sat1/hk/16664/1666404558.g3.`
The spikes in irig_time caused the start/end time to be wrong, and the frame counter ([PR#315](https://github.com/simonsobs/sotodlib/pull/315)) was running almost forever in the write_solution.
This is known issue from a loose cable in the hardware, which has now been fixed.
I added the IRIG correction process for both cases in latest `hwp` branch.
I also added an option to use 2nd encoder IRIG: `field_instance_sub: 'observatory.HBA2.feeds.HWPEncoder
`
I will make new PR to merge this modification.

IRIG timing spike in `/mnt/so1/data/ucsd-sat1/hk/16664/1666404558.g3.`
![image](https://user-images.githubusercontent.com/10991568/198227279-bb691c00-6578-4acc-9267-d3b02f9cf395.png)

IRIG timing is off from `/mnt/so1/data/ucsd-sat1/hk/16664/1666418967.g3`
![image](https://user-images.githubusercontent.com/10991568/198227208-450fa403-2024-4094-af58-f186b48e7231.png)

**Comment by yukisakurai** [comment]
We will have lots of warning but process should flow.
```
WARNING: sotodlib.hwp.g3thwp: a part of the IRIG time is incorrect, performing the correction process...
WARNING: sotodlib.hwp.g3thwp: a part of the IRIG time is incorrect, performing the correction process...
  29.543: writing solution /mnt/so1/users/ysakurai/sotodlib_dev/hwp/output/16664/1666400957.g3 (INFO)
  63.322: Processing /mnt/so1/data/ucsd-sat1/hk/16664/1666404558.g3 (INFO)
WARNING: sotodlib.hwp.g3thwp: a part of the IRIG time is incorrect, performing the correction process...
WARNING: sotodlib.hwp.g3thwp: a part of the IRIG time is incorrect, performing the correction process...
  88.614: writing solution /mnt/so1/users/ysakurai/sotodlib_dev/hwp/output/16664/1666404558.g3 (INFO)
 121.666: Processing /mnt/so1/data/ucsd-sat1/hk/16664/1666408161.g3 (INFO)
WARNING: sotodlib.hwp.g3thwp: a part of the IRIG time is incorrect, performing the correction process...
WARNING: sotodlib.hwp.g3thwp: a part of the IRIG time is incorrect, performing the correction process...
 143.086: writing solution /mnt/so1/users/ysakurai/sotodlib_dev/hwp/output/16664/1666408161.g3 (INFO)
 167.544: Processing /mnt/so1/data/ucsd-sat1/hk/16664/1666411763.g3 (INFO)
WARNING: sotodlib.hwp.g3thwp: a part of the IRIG time is incorrect, performing the correction process...
WARNING: sotodlib.hwp.g3thwp: a part of the IRIG time is incorrect, performing the correction process...
 188.617: writing solution /mnt/so1/users/ysakurai/sotodlib_dev/hwp/output/16664/1666411763.g3 (INFO)
 212.866: Processing /mnt/so1/data/ucsd-sat1/hk/16664/1666415365.g3 (INFO)
WARNING: sotodlib.hwp.g3thwp: a part of the IRIG time is incorrect, performing the correction process...
WARNING: sotodlib.hwp.g3thwp: a part of the IRIG time is incorrect, performing the correction process...
 234.126: writing solution /mnt/so1/users/ysakurai/sotodlib_dev/hwp/output/16664/1666415365.g3 (INFO)
```
