### ISSUE TITLE
Update detrend 

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sotodlib#349]
`tod_ops.detrend_tod` should really be detrending the data in place. It should also follow our more standardized conventions for passing kwargs.

**Comment by AERAdler** [comment]
Hi Katie, by detrending in place, do you mean it shouldn't call detrend_data?

**Comment by kmharrington** [comment]
I mean that it would be better if we didn't make another copy of the data in memory while detrending. The current setup currently takes a good bit of time and optimizing it would be nice.
