### ISSUE TITLE
Set up Automation of make-read-det-match

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sotodlib#364]
Once #345 is merged we should test the automation of this script for one of the on-going cooldowns. Ideally we want to test it from the beginning of a cooldown because that's when the most work is happening towards readout / detector setup.

**Comment by guanyilun** [comment]
Is there any example config file for simons1?

**Comment by kmharrington** [comment]
@davidvng  should have one or have an idea of how to set it up for SAT1

**Comment by davidvng** [comment]
@guanyilun I'm currently using this config file on simons1: `/mnt/so1/users/dnguyen/sat/db/read_det_config.yaml` which is then producing databases being used by this context file: `/mnt/so1/users/dnguyen/sat/db/p10r2_context.yaml`

**Comment by kmharrington** [comment]
Done!
