### ISSUE TITLE
load_preprocess_tod should be able to load subsets of detectors in a TOD instead of the entire thing

### ISSUE THREAD

**Issue by jseibert575** [simonsobs/sotodlib#370]
https://github.com/simonsobs/sotodlib/blob/c018a7c8cd9424e49911b90ae1a35175dbc83a96/sotodlib/site_pipeline/preprocess_tod.py#L144

In the function here, it would be great to be able to load smaller subsets of detectors instead of the entire TOD.

**Comment by kmharrington** [comment]
Plan to do this by making `load_preprocess_tod` take all the arguments of `context.get_obs()`
