### ISSUE TITLE
Bookbinder: Wiring frame copying

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sotodlib#374]
Started looking through the books on simons1 and noticed that I think something isn't copying correctly. Wiring frames should be copied straight from level2 --> level3 with the only difference being they might be moved a little around based on the Scan frame re-framing. 

That should mean that we can load a SmurfStatus object equally as well between the two levels. But:
```
import so3g
from spt3g import core

from sotodlib.io.load_smurf import SmurfStatus
book = "/mnt/so1/shared/site-pipeline/data_pkg/books/pton-tsat/obs/16735/obs_1673517465_tsat_1101111/"
SmurfStatus.from_file(book+"D_obs_crate_so04_slot2_000.g3")
```

is giving me some sort of key error on missing info in the frame. 

I've also noticed the the Ancillary frames in that book have many many wiring frames that are just empty. That also doesn't seem right.

**Comment by algadoreo** [comment]
> I've also noticed the the Ancillary frames in that book have many many wiring frames that are just empty. That also doesn't seem right.

_Wiring_ frames should be copied from the input with no changes, so those empty _Wiring_ frames must have been empty to begin with—or is that not the case?

**Comment by kmharrington** [comment]
I'm not actually sure. This data doesn't have HWP or Mount information in it right now, so I don't know what wiring frames are going into the Ancillary data. 

Now that I think about it, I'm not sure there should be wiring frames going into the Ancillary data. That should only come from detector info and those aren't going in Ancillary...
