### ISSUE TITLE
Bookbinder needs a unit test for multiple frame split times

### ISSUE THREAD

**Issue by jsyleung** [simonsobs/sotodlib#423]
Bookbinder currently doesn’t have a test for the case where there are multiple frame splits for the current buffered data. It’s supposed to be handled by the following block, but there is no test for it:

https://github.com/simonsobs/sotodlib/blob/a4f4c68bcca22c4623ff449963c2d7a6a7bf03b2/sotodlib/io/bookbinder.py#L1054-L1061

The test data should include one long frame within which there are at least 2 frame split events. To be comprehensive, the test should also include an instance where the split time is exactly the frame end time. Example:

```
frames:    |                 |                 |    |
splits:          ^     ^        ^       ^      ^     
```

**Comment by kmharrington** [comment]
now using different version of bookbinder
