### ISSUE TITLE
Bookbinder’s guess for sample interval will be wrong when too few samples

### ISSUE THREAD

**Issue by jsyleung** [simonsobs/sotodlib#424]
If the input frame has too few samples, it should not be using that to estimate the sample interval. It would be better to store the previous frame’s sample interval and use that instead.

https://github.com/simonsobs/sotodlib/blob/a4f4c68bcca22c4623ff449963c2d7a6a7bf03b2/sotodlib/io/bookbinder.py#L532

For the following, this is only a problem if `len(ts) == 1`, but it’s a possibility.

https://github.com/simonsobs/sotodlib/blob/a4f4c68bcca22c4623ff449963c2d7a6a7bf03b2/sotodlib/io/bookbinder.py#L548

**Comment by kmharrington** [comment]
now using different version of bookbinder
