### ISSUE TITLE
Bookbinder: Optimize filling of missing samples process

### ISSUE THREAD

**Issue by jsyleung** [simonsobs/sotodlib#429]
In #412, jlashner pointed out a number of things that can be improved/cleaned up in the process for filling in missing samples, but are not critical to its function:

1. I’m pretty sure the `[:self.maxlength]` in the following has been superseded by another line further down (L610), but I haven’t rigorously tested it.
https://github.com/simonsobs/sotodlib/blob/a4f4c68bcca22c4623ff449963c2d7a6a7bf03b2/sotodlib/io/bookbinder.py#L556

2. The method `fill_missing_samples` is called three times even though the missing samples are the same. This leads to the same “X missing samples detected” message being printed three times.
https://github.com/simonsobs/sotodlib/blob/a4f4c68bcca22c4623ff449963c2d7a6a7bf03b2/sotodlib/io/bookbinder.py#L598

3. The fallback block in case a timestamp list is not provided can probably be removed if there’s no anticipated use for it. If so, the Bookbinder needs to throw an error if it does not receive a reference timestamp list from the Imprinter.
https://github.com/simonsobs/sotodlib/blob/a4f4c68bcca22c4623ff449963c2d7a6a7bf03b2/sotodlib/io/bookbinder.py#L527-L528
And the unit test case with `smts == None` should also be removed here:
https://github.com/simonsobs/sotodlib/blob/a4f4c68bcca22c4623ff449963c2d7a6a7bf03b2/tests/test_bookbinder.py#L152

4. Update the name of the flag fields once that has been finalized (currently `flag_smurfgap` and `flag_hkgap`).

**Comment by kmharrington** [comment]
now using different version of bookbinder
