### ISSUE TITLE
Bookbinder does not check length of last output frame

### ISSUE THREAD

**Issue by jsyleung** [simonsobs/sotodlib#433]
When there are no more SMuRF files (from one particular wafer) to be read, Bookbinder will simply flush all remaining samples in the buffer in a single output frame without checking its length. This is because it calls `flush` directly (below), bypassing the length check in `__call__`. A potential solution is to invoke the FrameProcessor with an empty frame (to trigger the length check) just before the `flush` call:

https://github.com/simonsobs/sotodlib/blob/7f3497a9030566eb759fc06370c43b3ae3001d60/sotodlib/io/bookbinder.py#L1076-L1083

**Comment by kmharrington** [comment]
now using different version of bookbinder
