### ISSUE TITLE
Clarification on the Meaning of Time-Domain Data Processing

### ISSUE THREAD

**Issue by randomwangran** [simonsobs/sotodlib#435]
Hello, I came across your package containing software for time-domain data processing, but I am not quite sure what this term means. Can you please provide some clarification? I would appreciate it if you could explain it to me in simple terms, as I am not an expert in this field. Thank you very much for your help!

**Comment by kmharrington** [comment]
Hi @randomwangran  This is a software package for analyzing detector timestreams for Simons Observatory ([public website](https://simonsobservatory.org/)). Most of this development is very specifically focused toward the time domain data processing required to turn timestreams generated by transition-edge sensors detectors into maps on the sky. There are a lot of scientific of papers generated by previous experiments such as [Planck](https://www.cosmos.esa.int/web/planck/publications), [ACT (Atacama Cosmology Telescope)](https://act.princeton.edu/publications), Simons Array, SPT (South Pole Telescope) etc, that go through the type of analysis we're setting up to do here. Nearly all of those can be found for free on the arxiv https://arxiv.org/ or through links from their public websites.
