### ISSUE TITLE
Write "make-hwp-solutions" script

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sotodlib#450]
Based on the new HWP angle solutions plans, ([documented here](https://docs.google.com/document/d/1zLyMNPiGV36sLqhlkbJHo26oxd6vrRvXUetpvtrqIUw/edit?usp=sharing)), we now plan to use caldbs (ie. manifest dbs) to store, version, and load HWP angles for each observation. 

We need to write a site-pipeline script that can generate these angles.

**Comment by yukisakurai** [comment]
@glitter17 I created make-hwp-solutions branch and add template script. You can add angle g3 to sqlite(hdf5) translator function in g3thwp and call in this script.
