### ISSUE TITLE
Need a way to "just load a g3 file from a book" 

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sotodlib#514]
I suspect this will be an important debugging tool and that detector folks / lower level folks will want it. 

I have confirmed that `sotodlib.io.load_smurf.load_file` will not work for this as-is because we have renamed data --> signal and (the harder fix) the loader works out all the resonator name keys. It expects the names of the detector signals to be in the "r000" format  but we have re-named them all to readout ID. 

I think we should split out the functionality in `load_book` or something there instead of patching the `load_file` function. This is because that should also be loading the ancillary data as well.

**Comment by mhasself** [comment]
Addressed in #526
