### ISSUE TITLE
Mount positions not in the Site Books

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sotodlib#551]
It looks like the one time we've had detectors and mount readout at the same time, we have not gotten that data into the books. An example is here: `/so/staged/lati1/oper/16935/oper_1693514253_lati1_100/`

This is something we need tracked down as soon as possible

**Comment by mhasself** [comment]
The ACU Agent was not recording precision encoder data at that time.  The agent was being run in a degraded mode due to networking issues.

So the book is right -- there were no platform data to include.
