### ISSUE TITLE
Bookbinder does not bind the SATP boresight encoder

### ISSUE THREAD

**Issue by mhasself** [simonsobs/sotodlib#553]
Because [this line](https://github.com/simonsobs/sotodlib/blob/280db0a247d86c79f8a56a27c3a8ac03f43eca63/sotodlib/io/bookbinder.py#L192) checks for the wrong key.

The key "Corrected_Boresight" is correct.

Obviously the fix is trivial but this should be tested on the E2E system, and then I would like to inspect the output (cf #524).

Please consider this high priority, as we need the boresight position in the Books from day 1, which is nearly upon us.

**Comment by BrianJKoopman** [comment]
The E2E system is still having some issues following our recent network migration. I'll look into those problems more now.

**Comment by BrianJKoopman** [comment]
OK, I've solved the problem that I was running into. There are still some services offline following a reboot of that system, but I think everything else is working as expected.
