### ISSUE TITLE
Current Imprinter Issues

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sotodlib#602]
In M_index.yaml file

* need to write out the slot mask into the file so we can know which wafer slots are running
* `telescope` is not `sat` needs to be `satp1`
* `tube_slot` shouldn't be `stp1`. it's supposed to be `st1` (the LAT's are currently correct at least)
* we need `tube_flavor` as well

possible intermediate step would be obsdb getting it from the stream id names (ufm_**m**v19 is an MF wafer)

**Comment by mhasself** [comment]
Also #578

**Comment by kmharrington** [comment]
finished
