### ISSUE TITLE
Add Boresight or Corotator Position to ObsDb

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sotodlib#611]
We're going to want to be able to query / group by boresight position for the SAT, that's going to be one of the major data splits. We probably also want to track LAT Corotator position as well.

**Comment by AERAdler** [comment]
We have some of those in update_obsdb: there are roll_center and roll_throw keywords for observations, computed from boresight_enc (SAT) or el_enc and corotator_enc (LAT) See lines 253-263.
Do you want another keyword specifically for the corotator angle?

**Comment by kmharrington** [comment]
Hmm ok. I'm not seeing those in the database for `satp1`

**Comment by AERAdler** [comment]
Solved by re-generating one of the obsdb lines.
