### ISSUE TITLE
tests.test_hardware takes too long

### ISSUE THREAD

**Issue by mhasself** [simonsobs/sotodlib#62]
I think we should use smaller test cases, by default, so the tests are light enough to be run frequently.  This will encourage use of the tests.

In cases where performance "at scale" needs to be checked, individual tests can be run with additional options set; but that need not be the default.

**Comment by tskisner** [comment]
The run time of those tests is basically just the plotting.  In fact there is already an override to disable the plotting:

https://github.com/simonsobs/sotodlib/blob/master/tests/test_hardware.py#L30

This is used on travis to speed things up.  We could always make that the default.

**Comment by mhasself** [comment]
That would help... but it still takes ~45 seconds, with plotting disabled.

**Comment by tskisner** [comment]
Ok.  I can simulate a subset of the detectors to reduce that time if we need.  When someone is developing code and running tests locally, they probably just want to run the tests for the feature they are working on (not all of them).  We should add that feature to setup.py if needed.

If we are running all the tests on travis for a PR, I think it is ok for the total to take 5-10 minutes.  However, I agree that simple tests of hardware simulating should not be using up all of our time budget.

**Comment by mhasself** [comment]
@tskisner This continues to bug me... please address in the next week or so, or I can put in a fix.

**Comment by tskisner** [comment]
Sure, will reduce the number of wafers in the tests.
