### ISSUE TITLE
Restrict `in_place=False` "not working"? 

### ISSUE THREAD

**Issue by jlashner** [simonsobs/sotodlib#636]
This might be expected behavior, however it stumped me for a couple of hours today so I wanted to check if it's a bug / make the behavior known...

But it looks like when you restrict an axismanager with `in_place=False`, the new axis-manager that is returned does not have a deep-copy of all of the fields, allowing things like this to happen:
``` python3
obs_id = 'obs_1697164370_satp1_1111111'
am = ctx.get_obs(obs_id, dets=['sch_ufm_mv7_1696796495_4_003'], samples=(0, 100))
am2 = am.restrict('samps', (0, 10), in_place=False)
am2.signal += 20
plt.plot(am.signal[0])
```
![image](https://github.com/simonsobs/sotodlib/assets/4718487/003cbe98-cc4c-48b4-82ba-bb17323f0f28)

It makes sense why this is happening but it seems very unintuitive to me. Is this intended?

**Comment by kmharrington** [comment]
yeah I feel like this is the wrong sort of behavior we want. If in_place is false we should make actual copies.
