### ISSUE TITLE
Import in site_pipeline/make_det_info_wafer.py breaks running so-site-pipeline

### ISSUE THREAD

**Issue by chervias** [simonsobs/sotodlib#663]
[This line](https://github.com/simonsobs/sotodlib/blob/89f94ee1b5f4fb192db5381264c6efe3201b652a/sotodlib/site_pipeline/make_det_info_wafer.py#L8) fails with a ModuleNotFoundError when I try to run any script in so-site-pipeline, but it doesn't do anything in the rest of that script, so I think it can be safely commented.

**Comment by mhasself** [comment]
Resolved in #664
