### ISSUE TITLE
Include reason HWP angles are zero in ManifestDb writeout for make-hwp-solutions

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sotodlib#669]
Right now it looks like there are four difference reasons `_write_empty_solution_h5` could be called in `g3thwp`. And there's nothing in the hwp_solution info that says the empty solution was written. A field needs to be added to the database to indicate why this happened because otherwise there will continue to be a large overhead on investigating why there are zeros. (no hwp data would nicely mean "don't bother investigating" while "error in calculations" would indicate the need for follow up).

**Comment by ykyohei** [comment]
This issue is addressed by https://github.com/simonsobs/sotodlib/pull/676.
