### ISSUE TITLE
SATp1 HWP Angles Missing for SCR2

### ISSUE THREAD

**Issue by msilvafe** [simonsobs/sotodlib#725]
The HWP angle ManifestdB in `/so/metadata/satp1/manifests/hwp_angles` is missing angles for SCR2. This means that anyone using a context pointing to that dB cannot load SCR2 data. @ykyohei has generated an updated dB with those angles in it in his user space but it needs to be moved to the shared/official metadata directory.

**Comment by ykyohei** [comment]
I hope this will be addressed along with this https://github.com/simonsobs/site-pipeline-configs/pull/41
