### ISSUE TITLE
get_trending_flags sometimes cuts all detectors due to division by zero in _slopes calculation

### ISSUE THREAD

**Issue by mmccrackan** [simonsobs/sotodlib#968]
The function `get_trending_flags` in `tod_ops.flags` sometimes cuts all detectors due to a division by zero in the calculation of the slopes for each time chunk:

`_slopes = ((t * s).mean(axis=1) - t.mean() * s.mean(axis=1)) / (
            (t**2).mean() - (t.mean()) ** 2`

This leads to `inf` for `_slopes` and preprocessing will fail on the next step since no detectors remain.  An example observation where this occurs is:

obsid = 'obs_1718494724_satp3_1111111'
dets={'wafer_slot':'ws0', 'wafer.bandpass':'f150'}

Calculating some statistics of the `t` vector gives:

t.mean() = 1718494994.489052
(t^2).mean() =  2.953225046083927e+18
(t.mean())^2  = 2.953225046083927e+18
(t^2).mean() - (t.mean())^2 =  0.0 (this is the denominator)
np.min(t) = 1718494980.354052 
np.max(t)  = 1718495008.624052
t[-1] - t[0] = 28.269999980926514

The slope denominator should be zero if `t` is constant, but printing out the minimum and maximum of `t` shows that it is not.  The calculated denominator is still zero though.  Maybe this is a numerical precision issue?

**Comment by skhrg** [comment]
I agree that numerical precision seems likely, this can be helped by doing `t = timestamps - timestamps[0]`.  

A quick check on this:

```
import numpy as np

t = np.arange(1718494980.354052, 1718495008.624052, 1./200.)
print((t**2).mean())
print((t.mean())**2)
t -= t[0]
print((t**2).mean())
print((t.mean())**2)
```

prints:

```
2.953225046076446e+18
2.953225046076446e+18
2.953225046076446e+18
2.953225046076446e+18
```

I'll get a PR in ASAP since as time passes this will just get worse
