### ISSUE TITLE
Reductions of short observations

### ISSUE THREAD

**Issue by mmccrackan** [simonsobs/sotodlib#970]
During a recent site-pipeline catchup run, some observations gave warnings or failed for short observations.  One example:

`/global/u1/m/mmccrack/so_home/env/soconda_20240903_0.1.4/lib/python3.11/site-packages/scipy/signal/_spectral_py.py:600: UserWarning: nperseg = 65536 is greater than input length  = 62480, using nperseg = 62480
  freqs, _, Pxy = _spectral_helper(x, y, fs, window, nperseg, noverlap,`

This warning (not a crash) is from the PSD calculation in `scipy.welch` when the input length of the segment (`nperseg` in the config file) is longer than the observation.  The resulting PSD is therefore not averaged over many segments, though this might not be a significant concern.  If `nperseg` is not entered into the config, a value is calculated, so it might be useful to default to this method when the input value is too large.

Other issues can occur that are probably more common with very short observations, such as the case of Az not varying sufficiently (see https://github.com/simonsobs/sotodlib/issues/788) thus causing `get_trending_flags` to fail.  While not specifically associated with observation duration, excluding observations shorter than some minimum duration might be effective at avoiding both cases, particularly when running large numbers of observations.

**Comment by msilvafe** [comment]
We're handling errors for short observations (in particular nperseg selection in welch being longer than the number of samples in the observation) on a function-by-function basis and globally we are restricting our preprocess_tod runs to only include obs that are > 10 min now which largely removes all of these errors so I will close this issue.
