### ISSUE TITLE
Preprocess: Prep for next SATp1 Catchup

### ISSUE THREAD

**Issue by msilvafe** [simonsobs/sotodlib#977]
Starting point is satp3 catchup run w/ this [config](https://github.com/simonsobs/site-pipeline-configs/blob/20240819_satp3_catchup/satp3/20240819_satp3_cmb_preproc_cfg.yaml) on `20240819_satp3_catchup` branch of sotodlib. The changes we want to make are:

1. PR and merge branch `20240819_satp3_catchup` after moving profiling parts out to pwg-scripts.
2. Limit minimum duration to 10 minutes should alleviate issues in PR #970 and #788 
3. Fix handling of missing iir params in issue #969 
4. Fix wrapping of gapfilled signal as raised in issue #740

**Comment by mmccrackan** [comment]
The branch used for the satp3 and satp1 site pipeline catchup jobs is now merged so I'll close this.  #740 is resolved and the short observations are being handled by being excluded at runtime.  #969 remains a problem, though the source of the issue has been identified.
