### ISSUE TITLE
Preprocess: Use common preprocess functions

### ISSUE THREAD

**Issue by davidvng** [simonsobs/sotodlib#991]
#940 adds common functions used in several preprocess scripts to `util.py`. These functions include:
https://github.com/simonsobs/sotodlib/blob/38068f4798d49d8f4677a1ef134b7f801439bf30/sotodlib/site_pipeline/util.py#L310
https://github.com/simonsobs/sotodlib/blob/38068f4798d49d8f4677a1ef134b7f801439bf30/sotodlib/site_pipeline/util.py#L356
https://github.com/simonsobs/sotodlib/blob/38068f4798d49d8f4677a1ef134b7f801439bf30/sotodlib/site_pipeline/util.py#L390

After that PR is merged, `preprocess_tod` and `preprocess_obs` should be updated to import these functions.

**Comment by mmccrackan** [comment]
I think this is addressed in #1027 which superseded #1014, so I'll close.
